### ISSUE TITLE
RSS feed items

### ISSUE THREAD

**Issue by jules2689** [richardwu/news_scraper#12]
Should we use the pub date and title from the RSS feed, or at least offer it?
The latter so this is not coupled to Google RSS

![image](https://cloud.githubusercontent.com/assets/3074765/18249896/f77b98ce-7356-11e6-8a69-d8d7e6f8068e.png)

**Comment by jules2689** [comment]
@richardwu

**Comment by richardwu** [comment]
we could include a optional flag in the `GoogleNewsRss` constructor that also retrieves `pubDate` and other Google RSS metafields in the `extract` method.

**Comment by jules2689** [comment]
Looking again, I think it would require a refactor I think, not sure its worth tbh
