### ISSUE TITLE
Trainers

### ISSUE THREAD

**Issue by jules2689** [richardwu/news_scraper#5]
Trainers are a kind of flow. The take an article's HTML and guide a user through selecting a series of patterns from a defined set of preset patterns.  Right now, these patterns are defined from a preset series of patterns, but I can see a point where we are guided to select a section of (prettified and sanitized) HTML. This is one possibility of many, so we need a solution that allows us the extensibility to add new methodologies of adding and determining patterns.
## Concepts
- _Patterns:_ This can currently be a CSS/Xpath pattern and is used to extract information from an HTML article. It might make sense to validate custom defined xpath and css tables
- _Presets:_ These presets are things that map to more standardized patterns such as `og-description`
- _Domain Patterns:_ These are a set of patterns that describe extraction methods for all properties of an article.
- _Article:_ An article is an instance of HTML on which presets should be defined. Articles can usually be assumed to maintain the same layout for a given domain, and so mappings are done by domain.
#### Article ETL
- Given a url for an article, we check if we currently have a defined set of patterns for the given URL.
- If we do, then we try to transform the data from the article. If it fails to extract correctly, we should consider the predefined patterns to be invalid (maybe the website changed their layouts or something) and we should move to the case where we redefine patterns (in development) or log a fatal error (in production).
- If we do not, then we need to determine the patterns to use to extract the data. This is where our training flow starts.
#### Training
- Given an instance of an article, we are able to start a semi-automated series of predefined pattern selections.
- Iterate through each piece of information to pull out information
  - Show the user the possible options and the results based on the option
  - If the user selects a predefined option, then we are done. Record this into "domain patterns"
  - If the user selects a custom option, then we should validate it is a valid css/xpath option and show the resulting extraction using it. Have the user confirm it is correct
- Once the user has selected all information, then we are done. Record this to the scrapers.
- The next article ETL flow should use a new reloaded set of scraper patterns.
## Trainer Flow Isolation of Concepts

These are subject to change as we build this out.
- A master trainer flow will manage the concepts (models)
  - Presets (statically loaded and defined - maybe saving?)
  - Domain Patterns, a 1..n model of the patterns for an article
  - Article - likely just the transformer::article
- The master flow might control the flow of sub-flows. Examples include:
  - A Preset seletor flow
  - etc.

More TBD

**Comment by richardwu** [comment]
> If we do, then we try to transform the data from the article. If it fails to extract correctly, we should consider the predefined patterns to be invalid (maybe the website changed their layouts or something) and we should move to the case where we redefine patterns (in development) or log a fatal error (in production).

I don't think we should assume the pattern is invalid based on 1 (or N) instances of nothing being extracted. It's very possible that the author for a given article A for some domain D fucked up the formatting/html for article A. (See 1. below for proposed solution)

> If we do not, then we need to determine the patterns to use to extract the data. This is where our training flow starts.

Ideally, someone should be able to run this scraper every N minutes/hours/days without interruption. This means that we can't initiate the manual trainer flow during scraping.

What I'm thinking is that we have a structured log of:
1. Articles (domains) that had a) a scrape pattern defined but b) returned blank fields (some or all)
2. Articles (domains) that do not have a scrape pattern defined and were encountered during scraping

After a scraping run, we could output a summary of the 2 log files ^, and provide a rake task that will:
1. Initiate the trainer flow
2. Re-scrape the articles that were missed in the log files

**Comment by jules2689** [comment]
> I don't think we should assume the pattern is invalid based on 1 (or N) instances 

How do we detect the patterns being invalid then?

>  It's very possible that the author for a given article A for some domain D fucked up the formatting/html for article A.

That's highly unlikely. Most places will not provide html for people to make, but would rather have automated/generated articles - at least reputable places (i'd think)

> This means that we can't initiate the manual trainer flow during scraping.

yea I never meant in production - this would be during development only / training.

> Ideally, someone should be able to run this scraper every N minutes/hours/days without interruption. 

yes, that is the intention.

> What I'm thinking is that we have a structured log of:

Good idea 👌

**Comment by richardwu** [comment]
> How do we detect the patterns being invalid then?

An invalid pattern would return a blank string when using `Nokogiri::HTML#css/xpath`. However, for some fields like `section`, we can't assume the author will always specify that for a given article, especially if we include optional `data_type`s later on.

> That's highly unlikely. Most places will not provide html for people to make, but would rather have automated/generated articles - at least reputable places (i'd think)

It's unlikely but it happens. I think the best option is to log it and let the developer decide what to do with that article. The rake task would prompt the developer to check/re-enter the pattern anyways.

**Comment by jules2689** [comment]
> The rake task would prompt the developer to check/re-enter the pattern anyways.

Maybe the log can have a "maybe this is invalid" if the majority of fields are empty?

**Comment by richardwu** [comment]
> Maybe the log can have a "maybe this is invalid" if the majority of fields are empty?

That was what I was thinking 👍 . It would have to be separate from the articles without a scrape pattern defined at all though.

**Comment by jules2689** [comment]
Implementation of it is irrelevant for now but ya :+1:

**Comment by jules2689** [comment]
So this is done by #7
