### ISSUE TITLE
Convert everything to symbol keys

### ISSUE THREAD

**Issue by richardwu** [richardwu/news_scraper#8]
Our main YAML file, `article_scrape_patterns` is currently written with string keys.

We could convert everything to symbols to reduce the complexity of switching between the two (e.g. https://github.com/richardwu/news_scraper/blob/5168d782a84eac9cd9773aea46af67f340dcd38a/lib/news_scraper/trainer/presets_selector.rb#L49).

Thoughts? @jules2689

**Comment by jules2689** [comment]
thats the data type array, I dont think you can define symbols in arrays, things without quotes in yaml are strings (the quotes in the data types array are unnecessary)

**Comment by richardwu** [comment]
Apparently you can 
![image](https://cloud.githubusercontent.com/assets/10563314/18192096/fc823cac-709e-11e6-9776-eb29a228b5f4.png).

**Comment by jules2689** [comment]
oh weird, i guess I never thought of that syntax

**Comment by jules2689** [comment]
it only removed a `.to_sym` and changes up the yml file... so its a small change i wouldnt have any opinions on. Might make things easier in the future?

**Comment by jules2689** [comment]
we could also make it all strings - dunno why there are .to_syms everywhere but we seem to be able to go either way if we want

**Comment by richardwu** [comment]
I like symbols more because they show up more prominently in my syntax highlight 😄

**Comment by richardwu** [comment]
Also hash rockets blow
